# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: apt-get update -y && apt-get install maven -y && apt-get install docker.io && docker build -t mahi .
  displayName: 'Run a one-line script'


